### ISSUE TITLE
newline or <br /> tag will get duplicated 

### ISSUE THREAD

**Issue by sk29110** [Tarik02/html-substring-js#10]
When I am passing br tag
or \n somehow they are duplicated so you will be extra newline

**Comment by sk29110** [comment]
When I am passing <br /> or \n somehow they are duplicated so you will be extra newline

**Comment by tarik02** [comment]
Please, leave a test.

**Comment by sk29110** [comment]
the description of the problem is added later. let me know if you need more explanation 

![MfTui1nlpX](https://user-images.githubusercontent.com/626182/57588667-50d81680-74cc-11e9-8989-71c9dcb1f097.png)

**Comment by tarik02** [comment]
That's strange. I will fix this tonight.
