### ISSUE TITLE
Input with &amp; changes its value

### ISSUE THREAD

**Issue by rokerkony** [Tarik02/html-substring-js#12]
Hi, we found one issue which is braking the output when running through this substring.

```js
const htmlSubstring = require('html-substring').default;

const strLength = 1000;
const input = 'K&amp;M';

expect(htmlSubstring(input, strLength)).toEqual(input);
```

The expected behavior is that the input doesn't change but unfortunately, it does.

The current result of the test above is:
```
Expected: "K&amp;M"
Received: "&amp;KM"
```

**Comment by tarik02** [comment]
Fixed in version 1.8.1
