### ISSUE TITLE
ampersand problem

### ISSUE THREAD

**Issue by sk29110** [Tarik02/html-substring-js#9]
When I sent & to the function it gives me error. Is it the function's limitation?

 `Expected matching ';' to '&' at offset ${offset}`,

**Comment by tarik02** [comment]
Show the source code with that problem. Is that a [valid](https://validator.w3.org/) HTML? Ampersand is used to be used for printing [special symbols](http://rabbit.eng.miami.edu/info/htmlchars.html) while ampersand itself is printed using `&amp;`. So, when the parser sees `&` inside text, it waits for `;`, printing the text unchanged between `&` and `;`.

**Comment by sk29110** [comment]
I see. Thank you!

**Comment by tarik02** [comment]
Meanwhile, `${offset}` is really a bug, so that should be fixed.

**Comment by tarik02** [comment]
Also, I will make changes to allow using just an ampersand.

**Comment by tarik02** [comment]
More info: https://www.w3schools.com/html/html_entities.asp

**Comment by tarik02** [comment]
That's strange that you get `${offset}` in your error message...
